- name: setup catalogue microservice
  hosts: catalogue
  become: yes
  tasks: 
  - name: setup NPM(dependencies) source
    ansible.buildin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  - name: install NodeJS
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: check user exist ot not if not exist create
    ansible.builtin.command: id roboshop
    register: roboid
    ignore_errors: true
  - name: create roboshp user
    ansible.builtin.user:
      name: roboshop
    when: roboid.rc!= 0

  - name: check directory exist or not if not create
    ansible.builtin.stat:
      path: /app
    register: dir

  - name: print the dir stat
    ansible.builtin.debug:
      msg: "output: {{dir}}"

  - name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory
    when: dir.stat.exists == False # This is boolean so no queots required

  - name: Download catalogue code or artifacts 
    ansible.builtin.get_url: 
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
  - name: extract catalogue artifacts to /app
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    ansible.builtin.yum:
      name: npm
      state: installed

  - name: setup SystemD Catalogue Service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service 

  - name: daemon-reload catalogue
    ansible.builtin.systemd_service: 
     daemon_reload: true

    

                             
  


      


