- name: setup catalogue microservice
  hosts: catalogue
  become: yes
  tasks: 
  - name: setup NodeJS repos
    ansible.builtin.shell: curl -sL "https://rpm.nodesource.com/setup_lts.x | bash"
 
  - name: install NodeJS
    ansible.builtin.yum:
      name: nodejs
      state: installed

  - name: check user exist or not if not exist create
    ansible.builtin.command: id roboshop
    register: roboid
    ignore_errors: true

  - when: roboid.rc!= 0
    name: create roboshp user
    ansible.builtin.user:
      name: roboshop

  - name: check directory exist or not if not create
    ansible.builtin.stat:
      path: /app
    register: dir

  - name: print the dir stat
    ansible.builtin.debug:
      msg: "output: {{dir}}"

  - when: dir.stat.exists == False # This is boolean so no queots required
    name: create /app directory
    ansible.builtin.file:
      path: /app
      state: directory
    
  - name: Download catalogue code or artifacts 
    ansible.builtin.get_url: 
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp

  - name: extract catalogue artifacts to /app
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes

  - name: install npm dependencies
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: setup SystemD Catalogue Service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service 

  - name: daemon-reload catalogue
    ansible.builtin.systemd: 
      daemon_reload: true
  
  - name: copy mongo repo to yum.repos.d
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongodb client
    ansible.builtin.yum:
      name: mongodb-org-shell
      state: installed
  
  - name: load mongo data
    ansible.builtin.command: mongo --host mongodb.awsdevops.site < /app/schema/catalogue.js
    
  - name: restart catalogue
    ansible.builtin.service:
     name: catalogue
     state: restarted
     enabled: true

                             
  


      


