- name: install payment component
  hosts: payment
  become: yes
  tasks:
  - name: install python 3.6
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
     - pythone36
     - gcc
     - python3-devel
    