- name: install payment component
  hosts: payment
  become: yes
  tasks:
  - name: install python 3.6
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
     - pythone36
     - gcc
     - python3-devel
    
  - name: chack roboshop user exist or not
    ansible.builtin.command: id roboshop
    register: out
    ignore_erros: true

  - wehn: out.rc != 0
    name: create roboshop user
    ansible.builtin.user:
      name: roboshop

  - 