- name: install rabbitmq component
  hosts: rabbitmq
  become: yes
  tasks:
  - name: setup rabbitmq repo scrip
    ansible.builtin.shell: curl -s "https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
      
  - name: setup rabbitmq repos
    ansible.builtin.shell: curl -s "https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"
  
  - name: install rabbitmq server
    ansible.builtin.yum:
      name: rabbitmq-server
      state: installed
      