- name: install shipping component
  hosts: shipping
  become: yes
  tasks:
  - name: install maven fro shipping service
    ansible.builtin.yum:
      name: maven
      state: installed
  
  - name: check user roboshop exists or not
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true

  - when: out.rc != 0
    name: create user roboshop
    ansible.builtin.user:
      name: roboshop

  - name: check /app directory exists ar not
    ansible.builtin.stat:
      path: /app
    register: dir

  - name: print directory stats
    ansible.builtin.debug:
      msg: " OUTPUT: {{dir}}"

  - when: dir.stat.exists == False
    name: create /app directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: download and unarchive the shipping artifacts
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /app
      remote_src: yes

  - name: download dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: rename jar file name
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app

  - name: copy shipping service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: daemom reload
    ansible.builtin.systemd:
      name: shipping
      daemon_reload: true

  - name: install mysql
    ansible.builtin.yum:
      name: mysql
      state: installed

  - name: load shipping component data
    ansible.builtin.command: mysql -h mysql.awsdevops.site -uroot -pRoboShop@1 < /app/schema/shipping.sql 

  - name: restart and enable mysql
    ansible.builtin.service:
      name: mysql
      state: restarted
      enabled: true
       










  